export default {
  KEY: 'KEY',
  TICKET_DATA: 'TICKET_DATA',
  SORT_DATA_PRICE: 'SORT_DATA_PRICE',
  SORT_DATA_FAST: 'SORT_DATA_FAST',
  SORT_DATA_OPTIMAL: 'SORT_DATA_OPTIMAL',
  FILTER_DATA_ALL: 'FILTER_DATA_ALL',
  FILTER_DATA_ONE: 'FILTER_DATA_ONE',
  FILTER_DATA_TWO: 'FILTER_DATA_TWO',
  FILTER_DATA_THREE: 'FILTER_DATA_THREE',
  FILTER_DATA_NO_TRANSFER: 'FILTER_DATA_NO_TRANSFER',
}
